#ifndef MY_RUST_LIB_H
#define MY_RUST_LIB_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t rust_multiply(int32_t a, int32_t b);

#endif  /* MY_RUST_LIB_H */
